### ISSUE TITLE
Year of publishing

### ISSUE THREAD

**Issue by aminought** [EbookFoundation/free-programming-books#1926]
I'm not sure if anyone have suggested it already, but what do you think about signing of a year of publishing near with a title of a book?

**Comment by vhf** [comment]
Thanks for the idea. There are pros and cons.

I think the cons outweigh the pros:

* years aren't always good indicators of the current value of the information contained in a book
* would require a lot of work
* adds some overhead to the information the lists already contain

**Comment by aminought** [comment]
I think you are wrong. For me and, I'm sure, not only for me, year is a very good indicator of the information actuality. If I see a book published in 2003 and a book published in 2015, there is a big probability that I'll choose the second one because it contains more modern information.

**Comment by vhf** [comment]
I'm open to discussion on this topic, I'd be glad to take other opinions.

**Comment by eshellman** [comment]
One issue with tracking years is that many resources in the repo are being periodically updated. for the purposes of the repo, this would create more maintenance, more PR's to keep the info current. Side databases such as the one @vhf has worked on may be a better means of providing this info; I'm working an a git-tag-triggered metadata update scheme that might work, too.

Having said that, it would be useful, and perhaps not so much work, to add publication years only for resources that are older than ~5 years (~10 years?).

**Comment by brutalcrozt** [comment]
I am agree with @amninought, but @vhf also had good point. If we only measure the book by it's publication year, it will not make sense.

> would require a lot of work.

Then leave it to the community via PR. Encourage to submit a PR, even just for one book. Personally I feel no such things is literally free. It will cost time or will mostly. It's a return value as they found the list worthy.

> adds some overhead to the information the lists already contain
I am disagree with this, we know information now is cheap. What is expensive is understanding.

my point : it's worth add one more identifiers. Because surely it help give identifiers to suit the consumer needs :smile: . It's just like add one more optional column on database, a mother name. Reality shown not all child know their mother name.

**Comment by borgified** [comment]
could be an option if we could come up with a programmatic way to determine this. i mean it doesnt have to be perfect but if there was a way to automate for perhaps 50% of the cases with good accuracy then that might be a good starting point

**Comment by michaeljota** [comment]
@aminought I think that's exactly the point that @vhf means, maybe the older book it is better explaining or have better examples. It's old, what so ever, but for majority of software languages some old ways to do things still being right, even if they are not, it doesn't mean the book is worst compared to the newer.

Still, I agree that using the year of publish it's a good idea, even for those whom are currently in development.

**Comment by jarrydfillmore** [comment]
+1!

**Comment by rollingstones** [comment]
As a student myself, I tend to pick up an older version sometimes because new doesn't always mean nice.
There is some content which one might find useful but it is not present in the newer version because the author didn't feel so. 

Also, yes, that requires a lot of work but I feel that it will help people distinguish and find the book of their choice. I like the idea suggested by @eshellman .

**Comment by rknonchalance** [comment]
I'm only a novice so I could easily be wrong, but could there possibly be a midway route, like only indicate year of publishing for books and resources that are really old (like those from 2005 and older, or even the range from 2000 and older)? These could help some developers decide whether they want to have books and resources that are purely modern for the sake of gaining knowledge processed through the years or be open to legacy books that could, as said by others above, offer insights that modern books do not have. Nothing's wrong with adding years to all books, but that would require quite a lot of effort to track them all down at once, not to mention that many links are updated in the event that the authors decide to release a new edition of the book or simply update their postings. It's better to just track all of the legacy resources instead that won't change any time soon.

**Comment by theabstracture04** [comment]
It'd be useful, but also not so useful in another perspective. Signifying the year that a resource was published may validify and infer its reliability in terms of its information, but then again there's some other old resources still utilized to this day with new editions and iterations of itself. 

In this situation, though, it would be a nice little addition.

**Comment by eshellman** [comment]
Unless there are further comments, I will merge #2387 tomorrow and close this issue.

**Comment by eshellman** [comment]
Thanks for the comments, everyone!

**Comment by dzmitry-lahoda** [comment]
I know person who just left jail. I said he could learn JavaScript to earn money. Just use more latest free book which he can understand. He cannot choose latest easily or may end up learning old material.

Job interviewers will value person better if she speaks their language. Concept are old, but language changes. More modern books have more modern language.

For left to right persons, like me, year does not add overhead as I read only left bold linkable part.

I would be fine if and only if part of books will have year. It could be desired, but not obligate to pull with year.

**Comment by michaeljota** [comment]
@dzmitry-lahoda I had experience in web development, some of the easiest way to get a developer job nowdays, sadly. Anyhow, I have to stand up here and tell you that web development is not just do the job. Most of the time you'll use JS, witch itself is a very deep language, and hard to understand why somethings behave in the way they do, HTML and CSS. You may think that a newer book would tell you better stuff, but the true is that an old book is more likely to explain better because they did not have ES6, and Typescript, and this new stuff. Is you learn JS with ES6+ (Using Babel and things alike), then understand how JS works will be more difficult than learning old JS and then learn new syntax, because most of the time, that new syntax will be sugar for things that you already know. 

Hope this help you and your friend :D
