### ISSUE TITLE
Formatting for books with many versions

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#2353]
Many books, especially manuals, have an edition for every version of the software. Some of our lists are presenting one entry per version(for example PR #2350 ), others are only listing the latest version, sometimes a single link for multiple versions is presented.

What's the best way for these to be listed? When is a version so old we should omit it? Should the the practice be different for different language lists?

**Comment by scraggo** [comment]
I agree, I think they should be visually grouped. Here's a thought: sublists, most recent book first. One example:

* How to Think Like a Computer Scientist: Learning with Python - Allen Downey et al - [MULTIPLE EDITIONS]
    * [How to Think Like a Computer Scientist: Learning with Python, Interactive Edition](http://interactivepython.org/courselib/static/thinkcspy/index.html) (3.2)
    * [How to Think Like a Computer Scientist: Learning with Python](http://www.greenteapress.com/thinkpython/thinkCSpy/) - Allen B. Downey, Jeff Elkner and Chris Meyers (2.4)
    * [Think Python](http://www.greenteapress.com/thinkpython/) - Allen B. Downey (2.x & 3.0)

**Comment by eshellman** [comment]
that seems reasonable. Could you take a look at what the linter says about that? https://github.com/vhf/free-programming-books-lint

**Comment by scraggo** [comment]
I changed my mind, making the latest version the toplist element and the previous versions the sublist elements. I'll do a PR and you can tell me what you think. The linter didn't find any issues :)

**Comment by eshellman** [comment]
Thanks everyone who contributed, the suggestions are now implemented!

**Comment by tunggnu** [comment]
I have found an issue. When we have a title with more than 3 editions, we can't list them in descending chronological order, due to the rule "titles must be in alphabetical order".

For example, in the #5299 PR, my first commit could not pass Travis CI because it contains:

* [How to Think Like a Computer Scientist: Learning with Python, Interactive Edition](https://runestone.academy/runestone/books/published/thinkcspy/index.html) - Brad Miller, David Ranum, Jeffrey Elkner, Peter Wentworth, Allen B. Downey, Chris Meyers, and Dario Mitchell (3.2)
  * [How to Think Like a Computer Scientist: Learning with Python 3 (RLE)](https://openbookproject.net/thinkcs/python/english3e/) - Peter Wentworth, Jeffrey Elkner, Allen B. Downey, and Chris Meyers [(PDF)](https://www.ict.ru.ac.za/Resources/cspw/thinkcspy3/thinkcspy3.pdf)
  * [How to Think Like a Computer Scientist: Learning with Python 2nd Edition](https://openbookproject.net/thinkcs/python/english2e/) - Jeffrey Elkner, Allen B. Downey, and Chris Meyers (Using Python 2.x)
  * [How to Think Like a Computer Scientist: Learning with Python](https://greenteapress.com/wp/learning-with-python/) - Allen B. Downey, Jeff Elkner and Chris Meyers (2.4) (HTML, PDF)

I have to make a new commit to rearrange the editions and add ` 1st Edition` to the title of the 1st edition to meet the rule "titles must be in alphabetical order".

* [How to Think Like a Computer Scientist: Learning with Python, Interactive Edition](https://runestone.academy/runestone/books/published/thinkcspy/index.html) - Brad Miller, David Ranum, Jeffrey Elkner, Peter Wentworth, Allen B. Downey, Chris Meyers, and Dario Mitchell (3.2)
  * [How to Think Like a Computer Scientist: Learning with Python 1st Edition](https://greenteapress.com/wp/learning-with-python/) - Allen B. Downey, Jeff Elkner and Chris Meyers (2.4) (HTML, PDF)
  * [How to Think Like a Computer Scientist: Learning with Python 2nd Edition](https://openbookproject.net/thinkcs/python/english2e/) - Jeffrey Elkner, Allen B. Downey, and Chris Meyers (Using Python 2.x)
  * [How to Think Like a Computer Scientist: Learning with Python 3 (RLE)](https://openbookproject.net/thinkcs/python/english3e/) - Peter Wentworth, Jeffrey Elkner, Allen B. Downey, and Chris Meyers [(PDF)](https://www.ict.ru.ac.za/Resources/cspw/thinkcspy3/thinkcspy3.pdf)

The new commit passed the Travis-CI but the old editions are not in descending chronological order.

Are you okay with ascending chronological order of old editions? If not, you should limit the rule "titles must be in alphabetical order" to level 1 titles only.
