### ISSUE TITLE
"Opt-in required" in place of "Just fill the fields with any values"

### ISSUE THREAD

**Issue by packtpartner** [EbookFoundation/free-programming-books#2785]
Can we add the notation "Opt-in required" instead of "Just fill the fields with any values" for email address required to get the free book wherever applicable?

**Comment by eshellman** [comment]
Context for this: Several publishers of free ebooks want to collect email addresses of ebook users for marketing purposes. So in order to get a download link, users are asked to enter an email address. Publishers who do this include Packt, O'Reilly, Bookboon, Syncfusion, and Leanpub. Since before the Free Ebook Foundation was involved, Ebook listings for such items on Free-programming-books have been annotated  "*Just fill the fields with any values*", because while email addresses were requested, users declining to provide email addresses for whatever reason can just enter a fake email address and get the download link.

My view is that we need not discourage users from optionally joining a publisher's email list. By the same token, if an email address is really REQUIRED, the book is not really free; many users have valid reasons for not giving up a working email address, and reviewers shouldn't be forced to create an account to evaluate the worthiness of a submission.

I think the specific suggestion "*Opt-in required*" is problematic because if it's required, its not an "opt".

I think "*Email address requested*" would be acceptable. In any case, the notations should be applied uniformly, for fairness.

Other suggestions and opinions are welcome; we won't make a change unless there is rough consensus, or at least lack of major objection.

**Comment by shunchu** [comment]
I agree with @eshellman's comment. If a user is required to give something in order to get another thing in return, then it's not exactly free. As such, it should be explicitly noted so that a user knows what s/he's getting into before clicking a link.

**Comment by packtpartner** [comment]
Hi @eshellman,

So should we go ahead and make changes by adding "Email address requested" in our listings?
Also, to make it uniform do we have to make changes to all listings by changing "Just fill the fields with any values" to "Email address requested"?

**Comment by eshellman** [comment]
The community should get at least a week to comment before a decision is made. #2776 should go with "just fill in the fields" for now; we'll make a blanket change in a new PR if that's what's decided.

**Comment by packtpartner** [comment]
Okay, thanks!

**Comment by eshellman** [comment]
implemented

**Comment by packtpartner** [comment]
Hi eshellman,
Can we use "Email address requested" in our listings for future submissions?
