### ISSUE TITLE
Intro to Programming (is ES6)

### ISSUE THREAD

**Issue by fey** [EbookFoundation/free-programming-books#3039]
Hello, please check free course for beginners
[Youtube playlist ](https://www.youtube.com/watch?v=muFql8Z4sCg&list=PL-xu4i_QDSxcoDNeh8rx5-pHCCTOg0XsI)
[And interactive section with IDE](https://en.hexlet.io/courses/intro_to_programming)

I propose put the link at javascript section 
https://github.com/EbookFoundation/free-programming-books/blob/master/free-courses-en.md#javascript

**Comment by harrykar** [comment]
Hi fey 
Here all we are volunteers. Regardless of your hint (in issue form) i propose you to learn Git's usage(i assure you it's not so difficult) and propose what you find in terms of a public request(PR) because that's the right way to collaborate through Git in Github. 
If you are a Lunyx user or somehow are interested in Git through command line (CLI) take a look [here](https://progr-harrykar.blogspot.com/2018/10/basic-versioning-git.html) for the basic notions 
Moreover in that weekend hope finish/polish a tutorial(is in [Wiki](https://github.com/EbookFoundation/free-programming-books/wiki/Contribute-using-git's-Command-Line-User-Interface(CLI))) still in draft focused on how collaborate here through Git(CLI)

**Comment by fey** [comment]
https://github.com/EbookFoundation/free-programming-books/pull/3203
