### ISSUE TITLE
what to do with "curricula"? was: OSSU : Open Source Society University

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3076]
That one seems valuable  @eshellman  what you thing?
https://github.com/ossu/computer-science

**Comment by eshellman** [comment]
looks like something we should support. but where?
Seem to  it belongs with coursera, edx, mit ocw, etc. They're listed in "MOOC" but it seems they would fit better as a separate category in free-courses, because if you're looking for a course, you'd look there first.

I would welcome discussion and follow-on PRs on how to improve our handling of these resources.

**Comment by harrykar** [comment]
> looks like something we should support. but where?

Right now haven't idea a guy suggested it to me and after a very speedy look i put it here; had no time to explore further

> Seem to it belongs with coursera, edx, mit ocw, etc. They're listed in "MOOC" but it seems they would fit better as a separate category in free-courses, because if you're looking for a course, you'd look there first.
> 

They're listed in our "MOOC"? I guess no if i remember well

> I would welcome discussion and follow-on PRs on how to improve our handling of these resources.

Yep when i have time i explore  OSSU further and hopefully who has just used it and hear us please put down a message
