### ISSUE TITLE
Broken Spanish book link

### ISSUE THREAD

**Issue by aalonso99** [EbookFoundation/free-programming-books#3357]
Links to Spanish "Aprenda C++ avanzado como si estuviera en primero" and "Aprenda C++ básico como si estuviera en primero" are broken. 
Also I checked the documents in other websites, none of them official, and it is from Navarra's University. I cannot find the originals and there is no note about their license, so I am not sure if they really are open and free to use. 

Thank you for maintaining this repo :)

**Comment by rosepac** [comment]
> Links to Spanish "Aprenda C++ avanzado como si estuviera en primero" and "Aprenda C++ básico como si estuviera en primero" are broken.
> Also I checked the documents in other websites, none of them official, and it is from Navarra's University. I cannot find the originals and there is no note about their license, so I am not sure if they really are open and free to use.
> 
> Thank you for maintaining this repo :)

I don't understand what the real problem is. Nor what you do not understand. 

The freedom of use of the file in question is beyond doubt, since the file is written in the form of a university article; and the author himself exposed it to the public without any problem, for its use.

The fact that the author wanted to take that university article and transform it into an edited book.

That would not change the original file, nor its right to use. It is not a public domain book, nor under a creative commons license. In fact, it is not a book.

It is a university article. So it can be used for personal, learning or study use of the subject in question. Without any kind of problem.

In fact, the author has many other articles of similar nature, and in no case did he expose any type of license within them.

That same act. It defines us, because and for what, those files have been created? 

The only thing I miss in this case. Is that within the author's list of articles. This one in particular is marked as "Ruano Training". It is supposed to be a sutdy academy. What is absolutely impossible. Because you are not going to create a book for an academy with all the official typing of the university.

In any case, they are books that are surely out of date.  And if the author would like to license them. They would be new versions of the documents of that time and under another type of edition. I understand In this case there is no book or edited, nor of the author, nor in the redirection of the page of the University..

If we look a little deeper. The author, happened to the university [of madrid in 2002](https://cima.unav.edu/detalle-noticias-inmunologia-e-inmunoterapia/-/asset_publisher/8Ha8/content/2019_06_03_tecnun-javier-garcia-de-jalon-ingeniero-laureado-por-la-real-academia-de-ingenieria/10174?tituloNoticia=javier-garcia-de-jalon-ingeniero-laureado-por-la-real-academia-de-ingenieria&fechaNoticia=03-06-2019)

The document is used by other universities. 
* [INGENIEROS DE CAMINOS, CANALES Y PUERTOS de A Coruña](http://caminos.udc.es/info/asignaturas/grado_tecic/705/Bibliografia/TextosPDF/AprendaCPPComoSiEstuvieraEnPrimero-V2_JGarciaDeJalon.pdf) and others of his documents are used by others such as the University of Oviedo.

* [Linkedin](https://www.linkedin.com/in/javier-garc%C3%ADa-de-jal%C3%B3n-de-la-fuente-068078a/?originalSubdomain=es)

* [Artículos de Javier García de Jalón](https://scholar.google.es/citations?user=61xmH6UAAAAJ&hl=es&oi=sra)

**Comment by eshellman** [comment]
Are the links working?

**Comment by aalonso99** [comment]
> Are the links working?

Currently, access is denied.

**Comment by eshellman** [comment]
maybe @rosepac can submit a PR?

**Comment by SethFalco** [comment]
@eshellman Just want to check with you, it looks like this issue can be closed?

https://github.com/EbookFoundation/free-programming-books/pull/4181/files#diff-06af0d92444a8bf7277615e4c4e7fdbbe2fface4acbb241d772ce8391931d6a0R132
 
They were both fixed in the referenced PR, the links were replaced with Web Archive links.
