### ISSUE TITLE
Resource for Graphics Programming and Unix

### ISSUE THREAD

**Issue by chiragm123** [EbookFoundation/free-programming-books#3548]
Unix Book:https://homepages.uc.edu/~thomam/Intro_Unix_Text/TOC.html
Graphics Programming Resource:https://www.scratchapixel.com

**Comment by Sant268** [comment]
[https://www.cs.csustan.edu/~rsc/CS3600F00/Notes.pdf]
(Notes for a Computer Graphics Programming Course)
 [http://160592857366.free.fr/joe/ebooks/ShareData/Game%20Graphics%20Programming%20By%20Allen%20Sherrod.pdf]
(Game Graphics Programming)

**Comment by eshellman** [comment]
The Game Graphics Programming link does not look authorized.

**Comment by Sant268** [comment]
> The Game Graphics Programming link does not look authorized.

Hello, sorry I'm new here. What would be considered as 'authorized'?

**Comment by eshellman** [comment]
We do not include links to books that are posted without authorization of the author/publisher. Because

1. It could jeopardize the whole list.
2. The links get removed and we're stuck with 404s and an admin burden.
3. We want to support authors/publishers who willingly make their books free!

Please read https://github.com/EbookFoundation/free-programming-books/CONTRIBUTING.md

**Comment by GintasS** [comment]
#4223
