### ISSUE TITLE
Adding free programming books in Traditional Chinese

### ISSUE THREAD

**Issue by Jeremy850407** [EbookFoundation/free-programming-books#4160]
There is free_programming_books in simplified Chinese, I wonder if I can add Traditional Chinese version

**Comment by 199911** [comment]
There are a few resources in free-programming-books-zh.md is in Traditional Chinese.
Feel free to add new resources to it.

**Comment by eshellman** [comment]
feedback in this issue from the community is welcome. Splitting out a zh_CN the from the zh list would make a long list easier to use, but could hide titles as well. For a courses page with video content the issue is quite different as Mandarin and Cantonese are completely different spoken languages. Perhaps a better way to go is to add annotations to a single list to indicate traditional vs simplified.

**Comment by Tharunkumar001** [comment]
Can You assign this issue to me? @davorpa

**Comment by davorpa** [comment]
> Can You assign this issue to me? @davorpa

provide feedback first
