### ISSUE TITLE
Easier organization for access to files

### ISSUE THREAD

**Issue by kadhirash** [EbookFoundation/free-programming-books#4588]
I think it would be great to create folders on the main repository to distinguish between courses, podcasts-screencasts, books, interactive-tutorials, etc. for a cleaner look as well as easier access to grab a resource.

In doing so, the README.md links would have to change as well to reflect the new folders.

**Comment by SethiPandi** [comment]
I do think it would be more organized to structure the repository with directories instead. Especially as more types and languages are introduced.

My only opinion is that if this were to be done, I would _assume_ that a folder by language might be more practical.

I haven't surveyed this, but I'd imagine it's more common for one to be after resources in a certain languages. In other words, a common scenario would _probably_ be an individual looking for any French resources, not an individual looking for books in any language. I think directories by language would better reflect this.

It makes more sense to collate all French resources in a single directory, rather than to have some French resources grouped by type in many different directories, where the user has to peek in and out of each of them?

This also makes it easier to see all resources in a particular language at once. If grouped by type, the only way to see every French resource is to access _every_ directory, making it more tedious to navigate.

**Comment by kadhirash** [comment]
Yeah that's true, I like the idea of separating by languages and putting the corresponding resources in there!

**Comment by eshellman** [comment]
what I've noticed is that the list of files is so long, the README is way below the fold. So I think organizing by genre would be more effective than by language. 

But remember, I think this change would result in merge conflicts for EVERY SINGLE OPEN PR. So probably not realistic to do until November, and then more likely December. I'll be needing some help with the cleanup- both of you have been very helpful. October has been a lot of work, but well worth the trouble, I think.

**Comment by kakashi215** [comment]
Count me in too!!!!!!

**Comment by eshellman** [comment]
any feedback on the files reorg?

**Comment by kadhirash** [comment]
@eshellman I like how it looks more organized now! Could possibly be more refined with "how to" and "contributing" directories as well

**Comment by eshellman** [comment]
I didn't do those mostly because the link structure is a bit more complicated. And I wanted to see how things looked. Having them at the top level surfaces them better, too. So I'm inclined to leave them where they are, at least for a while. If we get a lot of translations we'll need to do something.
