### ISSUE TITLE
Add new algorithm books 

### ISSUE THREAD

**Issue by yezz123** [EbookFoundation/free-programming-books#4796]
[Algorithm Design](http://www.cs.sjtu.edu.cn/~jiangli/teaching/CS222/files/materials/Algorithm%20Design.pdf) : Book by Jon Kleinberg and Éva Tardos
[Algorithms](http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf) : Book by Christos Papadimitriou, Sanjoy Dasgupta, and Umesh Vazirani

**Comment by adarshraghav** [comment]
Could I add a book too?

**Comment by yezz123** [comment]
@adarshraghav  Yeah you can add

**Comment by kadhirash** [comment]
Don't think these resources are actually "free" books right? 
@SethiPandi what do you think?

**Comment by SethiPandi** [comment]
I can find Algorithm Design on https://archive.org/ which I think makes that one count as free which is cool.

It should use this URL though, not the one in the original issue:
https://archive.org/details/AlgorithmDesign1stEditionByJonKleinbergAndEvaTardos2005PDF

It's the same file (equal SHA265 checksum), but it'll download like 15x faster from archive.org since the other server was shoddy.

---

I didn't see Algorithms by Christos Papadimitriou being free though, just a bunch of places to buy it.

**Comment by kadhirash** [comment]
Alright sounds good, I can work on a PR for it soon.
