### ISSUE TITLE
Mark up look strange on the site when using pipes `|`

### ISSUE THREAD

**Issue by computamike** [EbookFoundation/free-programming-books#5176]
It seems that the | in the link breaks the rendering
![C#](https://user-images.githubusercontent.com/464876/99858549-b73ff980-2b85-11eb-81bc-0cd2dcb04e77.png)

Renders correctly when viewing the page within GitHub editing tools, but renders incorrectly on the GH Pages site.

**Comment by eshellman** [comment]
not surprising I guess. Want to fix it?

**Comment by computamike** [comment]
hi @eshellman - I'm looking into it now...

**Comment by computamike** [comment]
For more information - I have developed a linter plugin for this issue, just trying to figure out how to contribute it.

https://github.com/computamike/remark-link-escape

Do I close this issue, or is that something that the team needs to do?

**Comment by eshellman** [comment]
Let's leave it open; hopefully it will be addressed tov=gether with  #5031

**Comment by davorpa** [comment]
Hi team

Although the nice @computamike's plugin was added as dependency in v2.2.0, this improvement was reverted in 2.3.0 (2020 Dec)

https://github.com/vhf/free-programming-books-lint/compare/v2.2.0...v2.3.0

@vhf CI action is now using last released version (v3.0.0) with last alphabetize requested features but not with vhf/free-programming-books-lint#12

https://github.com/EbookFoundation/free-programming-books/runs/3195091515?check_suite_focus=true#step:4:8

I don't know what about the status is in because I'm newbie, but it would be a nice point to reintegrate again before it rots into oblivion, it isn't  @eshellman?

**Comment by charlottetan** [comment]
Took me awhile to find the relevant page: https://ebookfoundation.github.io/free-programming-books/casts/free-podcasts-screencasts-en.html

Appears to be rendering fine now
![image](https://user-images.githubusercontent.com/4824630/135735312-eeef87da-7acd-4ece-9c97-83bc9ac380b8.png)

**Comment by davorpa** [comment]
> Took me awhile to find the relevant page: https://ebookfoundation.github.io/free-programming-books/casts/free-podcasts-screencasts-en.html
> 
> Appears to be rendering fine now

We know it. See the fix #5177. The vertical bar is escaped

**Comment by charlottetan** [comment]
Oh nice thanks! What is the remaining work on this issue?

**Comment by davorpa** [comment]
It also happens in Arabic courses file.

Is wellknown that pipes is the table markdown token. Seems that Kramdown don't deal well with it

**Comment by davorpa** [comment]
Needs linter replug in. See https://github.com/EbookFoundation/free-programming-books/issues/5176#issuecomment-890391432
