### ISSUE TITLE
GHP bad rendering on CONTRIBUTE & HOWTO (fa_IR locale)

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#5559]
## Problem

It seems that Github Pages engine doesn't deal fine rendering links for this RTL resources:

- https://ebookfoundation.github.io/free-programming-books/HOWTO-fa_IR.html
  ![image](https://user-images.githubusercontent.com/3125580/134902815-ff35bd1a-5112-4571-8b46-81c17c3253b2.png)
- https://ebookfoundation.github.io/free-programming-books/CONTRIBUTE-fa_IR.html
  ![image](https://user-images.githubusercontent.com/3125580/134904015-a5dd08c0-3413-457d-966b-374645de6d51.png)

It **works well in other markdown files** like books, courses... for the same locale.

## Solution

Maybe due to some issue with the `div` tag:
https://github.com/EbookFoundation/free-programming-books/blob/e629db6b05a72fd64a6b33feeeebbe830641cf10/HOWTO-fa_IR.md#L1-L5

Need some experiments to deal with this tag, and maybe apply on listings too.

**Comment by charlottetan** [comment]
Spent some time looking into this, it looks like Github's markdown and the `<div dir="rtl">` aren't playing well together. To fix it, all of the markdown syntax will need to be changed to regular HTML tags instead of markdown, which include not just the links but also the headings 😧

Tests/examples - Only a couple of links and headings changed:
Code: https://github.com/charlottetan/free-programming-books/commits/master/CONTRIBUTING-fa_IR.md
Github page: https://charlottetan.github.io/free-programming-books/CONTRIBUTING-fa_IR.html

Screenshot with highlighting to show what got changed:
![image](https://user-images.githubusercontent.com/4824630/135736382-ed9f78e1-4eaa-444f-885c-cc0005654267.png)

Somewhat related issue filed on Github's markup repo, although the issue here is with github pages' code, not markup since the .md files are rendered fine in Github itself: https://github.com/github/markup/issues/332

**Comment by davorpa** [comment]
> To fix it, all of the markdown syntax will need to be changed to regular HTML tags instead of markdown, which include not just the links but also the headings

It is an option. :bulb: The other may be to configure the Jekyll theme well using some gem

**Comment by charlottetan** [comment]
Thanks for the idea! Didn't realise there was that option, submitted a PR that fixes this issue

**Comment by davorpa** [comment]
As I coment in https://github.com/EbookFoundation/free-programming-books/pull/5810#discussion_r720825190 it's a bit weird why use directly `GFM` is a bit different of `kramdown` with `input: GFM` (default). Maybe, to investigate about it and report to Jekyll project @jekyll.

From default config docs: https://jekyllrb.com/docs/configuration/default/
```yml
# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
```

**Comment by charlottetan** [comment]
(Responded in https://github.com/EbookFoundation/free-programming-books/pull/5810#discussion_r720917920)
