### ISSUE TITLE
The 0-MOOC and Algorithms and Data Structures anchor tags not working

### ISSUE THREAD

**Issue by Harshita-Kohli** [EbookFoundation/free-programming-books#6508]
On clicking 0-MOOC and Algorithms and Data Structures on the webpage, we cannot jump to the respective sections on the page. This feature is not working only for these 2 links.
![a tags](https://user-images.githubusercontent.com/54809528/139463098-0f14dfe0-f15d-4760-a8e3-615343ab06bc.jpg)

**Comment by davorpa** [comment]
It works well on markdown files.

@charlottetan more issues with GMF

**Comment by charlottetan** [comment]
@davorpa bummer that parsing continues to be an issue!

I spent some time investigating and have two options available:

### 1. PR #6677 - We switch the parser back to Kramdown. (recommended)
We originally switched to GFM in PR #5810, before we realised we could use `markdown="1"` in the div as suggested by Kramdown in https://github.com/kramdown/parser-gfm/issues/28. I tried out their suggestion and it mostly works. There was one small issue where plain URLs were not automatically parsed, which means we have to write `[https://github.com](https://github.com)` instead of just `https://github.com`.

I have my github pages pointed to the branch for this PR and the pages can be viewed here:
* https://charlottetan.github.io/free-programming-books/docs/CODE_OF_CONDUCT-fa_IR.html
* https://charlottetan.github.io/free-programming-books/docs/CONTRIBUTING-fa_IR.html
* https://charlottetan.github.io/free-programming-books/docs/HOWTO-fa_IR.html

And this also results in the anchor tags working:
* https://charlottetan.github.io/free-programming-books/courses/free-courses-en.html

### 2.  PR #6678 - We modify the anchor tags and set them via HTML
When headings include special characters, instead of writing
```
### 0 - MOOC
### Algorithms & Data Structures
```
We do this instead
```
<h3 id="0---mooc">0 - MOOC</h3>
<h3 id="algorithms--data-structures">Algorithms & Data Structures</h3>
```
I don't like this approach as much, like you point out in https://github.com/EbookFoundation/free-programming-books/pull/6678/files#r790243208, this requires a lot of extra effort to make sure it's always right. On top of that, there are many files we'd have to go through to change this in.

**Comment by davorpa** [comment]
> @davorpa bummer that parsing continues to be an issue!
> 
> I spent some time investigating and have two options available:
> 

Thanks for your hard work :love_you_gesture: !!!

> ### 2. PR #6678 - We modify the anchor tags and set them via HTML
> When headings include special characters, instead of writing
> 
> ```
> ### 0 - MOOC
> ### Algorithms & Data Structures
> ```
> 
> We do this instead
> 
> ```
> <h3 id="0---mooc">0 - MOOC</h3>
> <h3 id="algorithms--data-structures">Algorithms & Data Structures</h3>
> ```
> 
> I don't like this approach as much, like you point out in [#6678 (files)](https://github.com/EbookFoundation/free-programming-books/pull/6678/files#r790243208), this requires a lot of extra effort to make sure it's always right. On top of that, there are many files we'd have to go through to change this in. Also sounds like it might not play well with the new search #6643.
> 
> Results here: [charlottetan/free-programming-books@`charlottetan-try-fix-anchors`/courses/free-courses-en.md](https://github.com/charlottetan/free-programming-books/blob/charlottetan-try-fix-anchors/courses/free-courses-en.md?rgh-link-date=2022-01-23T08%3A40%3A19Z) No github pages link since it's currently pointing to the other branch.

At this moment this second is discarded due to as we post in https://github.com/EbookFoundation/free-programming-books/pull/6678#discussion_r790243208

**Comment by charlottetan** [comment]
Yeah I think we should go with PR #6677. I also see more discussion in that PR on other possible permutations of the processor

**Comment by eshellman** [comment]
have asked to folks working on the search to comment. Thanks @charlottetan for looking at this.

**Comment by brogan20** [comment]
Switching to Kramdown (#6677) would be ideal here. #6678 would completely break the search engine and parser used in #6643.

**Comment by eshellman** [comment]
@charlottetan Seems to be consensus on #6677  Ready to merge?
