### ISSUE TITLE
Link to Intro to COBOL not working

### ISSUE THREAD

**Issue by unemployedtechie** [EbookFoundation/free-programming-books#6528]
The link to Introduction to COBOL is not working, it is returning a 404 page. Could not find any new link for the same:

https://supportline.microfocus.com/documentation/books/oc41books/lrintr.htm

**Comment by Harshita-Kohli** [comment]
I have found a link to the free pdf of the Introduction to COBOL. May I update the link?

**Comment by Tharunkumar001** [comment]
I have Proper COBOL link. Can You assign this issue to me? @unemployedtechie

**Comment by davorpa** [comment]
We are talking about this?

https://github.com/EbookFoundation/free-programming-books/blob/3b455abd3fc6271ea0a6e703ed2e3f239e15bf21/books/free-programming-books-langs.md#L564

Improves #5470

**Comment by Harshita-Kohli** [comment]
Yes. This link is giving 404 Page not found" error

**Comment by davorpa** [comment]
> I have Proper COBOL link. Can You assign this issue to me?

> I have found a link to the free pdf of the Introduction to COBOL. The link is working. May I update the link?

We should provide found alterative to check best option

**Comment by Harshita-Kohli** [comment]
Do you want me to send the alternative link?

**Comment by Harshita-Kohli** [comment]
This is the link that I have found. It is a link to a pdf named "Intro_to_OO_Programming_for_COBOL_Developers.pdf" https://supportline.microfocus.com/Documentation/books/VisualCOBOL/Intro_to_OO_Programming_for_COBOL_Developers.pdf

**Comment by unemployedtechie** [comment]
@Harshita-Kohli This is a different book I assume since this is not a general intro to COBOL but an intro to object oriented programming in COBOL. I think we should change the name of the entry altogether, otherwise it might be misdirectional.

**Comment by Harshita-Kohli** [comment]
@unemployedtechie Yes, I think it would be better to change the name of the entry. Maybe we can write: "Intro to OOP in COBOL"

**Comment by Harshita-Kohli** [comment]
May I work on this issue?

**Comment by davorpa** [comment]
Completely out of sync since #3527 (https://github.com/EbookFoundation/free-programming-books/commit/a5a0839fcef7356c7812676beafb1f6219dd9431#diff-155c33d4757abe5647ec769bf94ba48739ca4fe3fc50fd2cf8511c69910f4332L1068-R1067)
  - Last backup: https://web.archive.org/web/20170913062134/http://www-03.ibm.com/systems/z/education/skills_coursematerials.html

---
This is what we are searching

![image](https://user-images.githubusercontent.com/3125580/139558397-7bec7eac-ca60-4af7-9df0-4c4715fdf081.png)
Micro Focus Object COBOL™
  - Last backup: https://web.archive.org/web/20191002235341/https://supportline.microfocus.com/documentation/books/oc41books/lrtocc.htm

### SUCCESS :tada:

https://www.microfocus.com/documentation/object-cobol/oc41books/oppubb.htm

**Comment by Harshita-Kohli** [comment]
When I am making the required changes to the books in the forked repo and then pushing the changes on the original repo, it is showing that I want to merge 16 commits into the EbookFoundation:master. But I just want to merge a single commit which is related to COBOL and not the older commits. Could you please help me with this.
help.
![help](https://user-images.githubusercontent.com/54809528/139580319-bbe44dd1-1ba4-4378-8f46-23f5b637f264.jpg)

**Comment by davorpa** [comment]
> When I am making the required changes to the books in the forked repo and then pushing the changes on the original repo, it is showing that I want to merge 16 commits into the EbookFoundation:master. But I just want to merge a single commit which is related to COBOL and not the older commits. Could you please help me with this. help. ![help](https://user-images.githubusercontent.com/54809528/139580319-bbe44dd1-1ba4-4378-8f46-23f5b637f264.jpg)

You need reset/override your main forked branch with the upstream content. Only after that you'll get fresh branches. This happens because PR merges are made here using squash.

So...

---

**TIP OF THE DAY :nerd_face: :books: :computer:** How to refork an `upstream` without delete your `origin` repository.

Execute under a Terminal (bash...):
```shell
# clone repo (if not do it yet): https://www.atlassian.com/en/git/tutorials/setting-up-a-repository
git clone [YOUR_FORK_REPO_URL] free-programming-books
cd free-programming-books
# add upstream remote (if not added yet): https://www.atlassian.com/en/git/tutorials/syncing
git remote add upstream [FPB_REPO_URL]

# override origin with upstream
git fetch --all
git checkout master
git reset --hard upstream/master
git push origin master --force
```
In forked repositories is very common using branches to pull the contributions and leave `master`/`main` untouched. It prevents more than one headache when merge conflicts appear :wink:. Adopt [Git Feature Branch Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) is a good starting point for beginners. :rocket:

**Comment by Harshita-Kohli** [comment]
Thanks for all the tips🙂. It will help me a lot!
