### ISSUE TITLE
Don't have enough  Courses  and did not update courses (bn) and need to remove 1 book (that does not exist right now)

### ISSUE THREAD

**Issue by Mdkawsarislam2002** [EbookFoundation/free-programming-books#6867]
### Need to  Remove 
 - 1 Book (BN)= SL3 Framework - Code For Brain, Because this website does not exist right now

### Need to  Add This Bangla Courses 

 - Go
 - bootstrap 
 - SASS
 - TailwindCSS
 - JavaScript 
 - Node
 - React 
 - svelte
 - Vue
 - Typescript 

### sending PR But need help on How to handle this. seems everything is perfect 
[My PR](https://github.com/EbookFoundation/free-programming-books/pull/6868)

**Comment by LuigiImVector** [comment]
The main problem is that your editor, maybe because of some installed plugin, changes the style of the lists (`*` to `-`), to avoid it the easiest way is to edit the files with another "clean" editor. #6829 try to fix this problem.

Also be careful to insert the [correct number of blank lines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md#formatting) between sections.

**Comment by CleanMachine1** [comment]
I think this issue can be closed now!
