### ISSUE TITLE
Add contributor label in readme file 

### ISSUE THREAD

**Issue by Hariom8799** [EbookFoundation/free-programming-books#7885]
![194721540-e2c06f16-cdcf-4d0d-8f58-964f96d5fd95](https://user-images.githubusercontent.com/76242202/194737574-01255049-fdf7-4ad9-8525-549a55c8cf5e
Like that

**Comment by shrn01** [comment]
Hey @Hariom8799 can you elaborate on the issue?

**Comment by Hariom8799** [comment]
![194721540-e2c06f16-cdcf-4d0d-8f58-964f96d5fd95](https://user-images.githubusercontent.com/76242202/194767422-45ffa046-61be-43db-bc81-66f32495aa2e.png)
 Like that

**Comment by Krishnapro** [comment]
Hey, I want to work on this issue. can you please assign it to me?

**Comment by Shanna99** [comment]
i made a PR for this issue

**Comment by Sarthak0101130** [comment]
Can you assign me this issue??

**Comment by somiyaAgarwal** [comment]
Hey! I want to work on it . Can you assign it to me?

**Comment by shrn01** [comment]
Do we really need this?

**Comment by Sarthak0101130** [comment]
Issue says it not me !! Sent from Mail for Windows From: Sharan JSent: 16 October 2022 18:15To: EbookFoundation/free-programming-booksCc: Sarthak0101130; CommentSubject: Re: [EbookFoundation/free-programming-books] Add contributor label in readme file (Issue #7885) Do we really need this?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by eshellman** [comment]
we hVE TOO Mny contributors for this
