### ISSUE TITLE
The "Let us C" book is not free.

### ISSUE THREAD

**Issue by tran184** [EbookFoundation/free-programming-books#9216]
I think it's under copyright and should not be here :).
![Screenshot_20221120-132503](https://user-images.githubusercontent.com/30346378/202894555-beea65af-6f81-488e-87e5-0701e1b29c03.png)

**Comment by eshellman** [comment]
Almost everything we list here is "under copyright". However many copyright holders choose to make their work available for free. We allow links to Internet Archive because they have a robust copyright policy and will quickly remove things when they learn that they have been uploaded without permission. If this is the case, the publisher should report this to the Archive!

We reject hundreds of submissions every year that link to file sharing site including most commonly pdfdrive, because they clearly do not have the rightsholder's permission.

We also consider PRs removing such links based on available information. In your case, you should provide more context. For books like this, it often happens that rights revert to the author.

To report this to the Archive, the rightsholder should report:

https://archive.org/details/let-us-c/

An exact description of where the material about which you complain is located within the Internet Archive collections;
Your address, telephone number, and email address;
A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;
A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the owner of the copyright interest involved or are authorized to act on behalf of that owner; and
Your electronic or physical signature.
The Internet Archive Copyright Agent can be reached as follows:

Internet Archive Copyright Agent
Internet Archive
300 Funston Ave.
San Francisco, CA 94118
Phone: 415-561-6767
Email: [info@archive.org](mailto:info@archive.org

**Comment by tran184** [comment]
Yeah, I'm not good at English. I think if "Let us C" can appear on
EbookFoundation then "The C Programming Language" can too. Also, Internet
Archive said that:
"Because we are a library, we pay special attention to books. Not everyone
has access to a public or academic library with a good collection, so to
provide universal access we need to provide digital versions of books. We
began a program to digitize books in 2005 and today we scan 4,000 books per
day in 18 locations around the world. Books published prior to 1927 are
available for download, and hundreds of thousands of modern books can be
borrowed
<https://openlibrary.org/subjects/in_library#ebooks=true&sort=edition_count>
through
our Open Library <https://openlibrary.org/> site. One of the Internet
Archive's missions is to serve people who have difficulty interacting with
physical books, so most of our digitized books are available to people with
print disabilities
<https://openlibrary.org/subjects/protected_daisy#ebooks=true&sort=edition_count>
(learn
about access here <https://archive.org/details/printdisabled&tab=about>)."

So modern book can only be borrowed to be legal.
Thanks for reading. Wishing you best health.

**Comment by eshellman** [comment]
I've asked Brian Kernighan about "the C programming Language". while the 2nd edition is on Archive, the authors were hoping to have an up to date version available, rather than have an obsolete version out there.

**Comment by tran184** [comment]
I mean there are copy of 1st and 2nd edition on Folkscanomy on archive.org
that can be downloaded and keep forever. I think those are easily to
download are not legal. Thanks for reading :).

**Comment by tran184** [comment]
And can you teach me, on archive.org, which books are legal to download?
There are many books that I want, but I'm afraid of legality.

**Comment by eshellman** [comment]
Sorry I can't give legal advice here, and copyright laws are different in every country, status can depend on date and location of publication, whether the author is living, whether a copyright has been renewed, etc. We depend a lot on the reputation (or lack thereof) of the site that we're linking to.

**Comment by tran184** [comment]
I think those books that are easily to download on archive.org are not
legal, as Brian said:

**Comment by tran184** [comment]
I think those books that are easily to download on [archive.org](http://archive.org/) are not legal, I emailed Brian Kernighan and he said:
"Thank you for your note.  [archive.org](http://archive.org/) is making the C book and many others
available illegally, at least for download, but it seems to be impossible
to get them to stop.

I am grateful to you for asking the question; most people don't.

Brian K"

**Comment by eshellman** [comment]
Right we don't link to that book. To remove our link to "Let us C" we'd need a PR with a clear, verifiable explanation.

**Comment by tran184** [comment]
No, we should provide strong reasons why we should put "Let us C" here.
