### ISSUE TITLE
python book 'can’t find that page'

### ISSUE THREAD

**Issue by dev7060** [EbookFoundation/free-programming-books#9493]
A Whirlwind Tour of Python
http://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.pdf

The link doesn't work.

**Comment by KairoQalb** [comment]
> A Whirlwind Tour of Python http://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.pdf
> 
> The link doesn't work.

Hi, I checked the link; it's not working because that page no longer exists. You can read it now on the O'Reilly learning platform with a 10-day free trial. Free PDF download is no longer available.

Here's the working link: https://www.oreilly.com/library/view/a-whirlwind-tour/9781492037859/

The content of this book is also available on GitHub as Jupyter Notebooks. 
Here's the repository link: https://github.com/jakevdp/WhirlwindTourOfPython

You can visit the author's site for reference ⇒ https://jakevdp.github.io/WhirlwindTourOfPython/

@eshellman since this book no longer has a free PDF download option, should I remove the link or replace it with the author's site?

**Comment by Rohit-Yadavv** [comment]
i am working on this please assign it to me

**Comment by eshellman** [comment]
go ahead!  No need to wait to be assigned. if you're worried about duplicated effort, just leave a message saying you're working on it - and mention issue # in your branch.
