### ISSUE TITLE
javatpoint and other cookie cutter sites

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#9801]
Take a look at https://www.javatpoint.com/sql-tutorial
There are significant errors or the first page, and I suspect its partly AI generated.
The site is full of advertising and lots of cookie cutter "tutorials".
With LLMs I expect these sites will proliferate.

For now, I'm not accepting PRs with links to this site or others like it.

Comment from the community is welcomed.

**Comment by 3R1Dev** [comment]
I copied a few paragraphs from the site and ran it through some free AI checkers, the result was that it was about 60% to 70% possible that it was generated by AI.

I noticed a few links looked off so I opened the website in a sandbox environment I use for analyzing malware. In the sandbox environment I first opened the YouTube link near the bottom of the page which seemed off due to it being shortened. That lead to the YouTube page for Javapoint but there was an usually request to allow consent to a few things.

Since I was analyzing the links in a sandbox I allowed it to see what would happen, then I followed the CSharp link on their YouTube about page back to the Javapoint site. There was another pop up about consenting this one asks if the site is allowed to make changes to files and folders on the visitors device, along with targeted ads and a few other things.

I allowed it and there was a malicious executable dropped on the sandbox machine, there are also a large amount of ads some of which are tied to known malicious sites.

I have attached some screenshots of the activity mentioned. 
You can see the report here: [https://app.any.run/tasks/ece87720-f9ff-4154-9962-b16cf79bc2c9](https://app.any.run/tasks/ece87720-f9ff-4154-9962-b16cf79bc2c9)

![Screenshot1](https://github.com/EbookFoundation/free-programming-books/assets/90082629/e3b137f9-0495-43de-b1b7-fcf529c639c3)
![Screenshot2](https://github.com/EbookFoundation/free-programming-books/assets/90082629/dab1fc7b-ead0-40ef-877c-b72b9ca54069)
![Screenshot3](https://github.com/EbookFoundation/free-programming-books/assets/90082629/e70adf62-d464-495a-9e4c-5d4a24807fc0)

**Comment by eshellman** [comment]
OMG!
